
######################## default configuration ####################
baseURL = "https://ccoss.org/"
title = "Cumbre de Contribuidores de Open Source Software (CCOSS)"
enableRobotsTXT = true
DefaultContentLanguage = "en"
RemovePathAccents = true


theme = "ccoss"
# post pagination
paginate = "8"


# output
[outputs]
home = ["HTML", "RSS"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  speaker = "speakers"

[sitemap]
  changefreq = 'weekly'
  filename = 'sitemap.xml'
  priority = 0.5

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
    identifier = "sedes"
    name = "sedes"
    url = "/sedes"
    weight = 2
  [[menu.main]]
    identifier = "sedes-virtuales"
    name = "Sedes Virtuales"
    url = "/sedes-virtuales"
    parent = "sedes"
    weight = 1
  [[menu.main]]
    identifier = "sedes-participantes"
    name = "Sedes Participantes"
    url = "sedes-participantes"
    parent = "sedes"
    weight = 2




  [[menu.main]]
  name = "Acerca de"
  URL = "/about"
  weight = 1

    [[menu.main]]
  name = "ConTRIBU"
  URL = "/contribu"
  weight = 3

  

  [[menu.main]]
    identifier = "agenda"
    name = "Agenda"
    url = "/agenda"
    weight = 1

  #[[menu.main]]
  #name = "Talleres"
  #URL = "/sessions/2021/"
  #weight = 2  

  #[[menu.main]]
  #name = "Ticket"
  #URL = "/ticket"
  #weight = 2

  #[[menu.main]]
  #name = "Conferencistas"
  #URL = "/speakers"
  #weight = 3


  #[[menu.main]]
  #name = "Patrocinadores"
  #URL = "/sponsors"
  #weight = 3

  #[[menu.main]]
  #name = "Reconocimientos"
  #URL = "/awards"
  #weight = 4
  
  #[[menu.main]]
  #name = "Kit virtual"
  #URL = "/kit-virtual"
  #weight = 5

  #[[menu.main]]
  #name = "Networking"
  #URL = "/networking"
  #weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "/faq"
  weight = 7

    [[menu.main]]
  name = "Edición 2021"
  URL = "/sessions/2021"
  weight = 8




#################### default parameters ################################
[params]
logo = "/images/logo-monochrome.svg"
home = "Home"

# Meta data
description = """La Cumbre de Contribuidores de Open Source Software (CCOSS) es un evento con charlas, talleres y mentorías para impulsar la contribución al open source en Latinoamérica."""
images = ["/images/CCOSS2022.jpg"]
twitter_user = "@RevistaSG"
email = "hola@ccoss.org"
author = "Software Guru"

# Google Analitycs
googleAnalytics = "G-M9TKWBTNE6" # your id
# search for blog page
search = true

disclaimer = """La Cumbre de Contribuidores de Open Source Software (CCOSS) es realizado por Software Guru en colaboración con Open Source México (OSOM)"""

start_date = "2022-11-10T10:00-05:00"
end_date = "2022-11-12T16:00-05:00"

[params.venue]
name = "Intel GDC"
street = "Av. del Bosque 1001"
city = "Zapopan"
region = "JAL"
zipcode = "45017"
country = "Mexico"


# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Boletos"
link = "/tickets"



############################# social icon ############################

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/playlist?list=PLnLzwYW6HOC6rbYIcrLnVkIMdG_9WB7vn"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:hola@ccoss.org"

[[params.social]]
icon = "fa-brands fa-slack"
link = "https://sg1.run/ccoss-slack"

[[params.footer_about]]
name = "?Quién organiza¿"
link = "/team/"

[[params.footer_source]]
name = "Código fuente del sitio"
link = "https://github.com/softwareguru/ccoss-website"

[[params.footer_previous]]
name = "Prospectus"
link = "/files/CCOSS2022 Hybrid - Prospectus.pdf"

[[params.footer_previous]]
name = "Código de Conducta"
link = "/coc/"

[[params.footer_resources]]
name = "Email"
link = "mailto:hola@ccoss.org"
