
######################## default configuration ####################
baseURL = "https://ccoss.org/"
title = "CCOSS"
enableRobotsTXT = true
DefaultContentLanguage = "en"

theme = "ccoss"
# post pagination
paginate = "8"


# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  tag = "tags"
  category = "categories"
  speaker = "speakers"
  track = "tracks"

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "/plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "/plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "/plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "/plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link="https://unpkg.com/bootstrap-table@1.18.0/dist/bootstrap-table.min.js"
[[params.plugins.js]]
link="https://kit.fontawesome.com/a6f10b653b.js"

############################## navigation ###############################
[menu]

  [[menu.main]]
    identifier = "sedes"
    name = "sedes"
    url = "/sedes"
    weight = 2
  [[menu.main]]
    identifier = "sedes-virtuales"
    name = "Sedes Virtuales"
    url = "/sedes-virtuales"
    parent = "sedes"
    weight = 1
  [[menu.main]]
    identifier = "sedes-participantes"
    name = "Sedes Participantes"
    url = "sedes-participantes"
    parent = "sedes"
    weight = 2




  [[menu.main]]
  name = "Acerca de"
  URL = "/about"
  weight = 1

    [[menu.main]]
  name = "ConTRIBU"
  URL = "/contribu"
  weight = 3

  

  #[[menu.main]]
  #  identifier = "program"
  #  name = "Agenda"
  #  url = "/schedule"
  #  weight = 1

  #[[menu.main]]
  #name = "Talleres"
  #URL = "/sessions/2021/"
  #weight = 2  

  #[[menu.main]]
  #name = "Ticket"
  #URL = "/ticket"
  #weight = 2

  #[[menu.main]]
  #name = "Conferencistas"
  #URL = "/speakers"
  #weight = 3


  #[[menu.main]]
  #name = "Patrocinadores"
  #URL = "/sponsors"
  #weight = 3

  #[[menu.main]]
  #name = "Reconocimientos"
  #URL = "/awards"
  #weight = 4
  
  #[[menu.main]]
  #name = "Kit virtual"
  #URL = "/kit-virtual"
  #weight = 5

  #[[menu.main]]
  #name = "Networking"
  #URL = "/networking"
  #weight = 5

  [[menu.main]]
  name = "FAQ"
  URL = "/faq"
  weight = 7

    [[menu.main]]
  name = "Edición 2021"
  URL = "/sessions/2021"
  weight = 8




#################### default parameters ################################
[params]
logo = "/images/logo-monochrome.svg"
home = "Home"

# Meta data
description = """La Cumbre de Contribuidores de Open Source Software (CCOSS) es un evento con charlas, talleres y mentorías para impulsar la contribución al open source en Latinoamérica."""
images = ["/images/CCOSS2022.jpg"]
twitter_user = ""
email = "hola@ccoss.org"
author = "Software Guru"

# Google Analitycs
google_analitycs_id = "UA-165970215-1" # your id
# search for blog page
search = true

disclaimer = """La Cumbre de Contribuidores de Open Source Software (CCOSS) es una iniciativa de Open Source México (OSOM) en colaboración con Software Guru."""



# Preloader
[params.preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Ticket"
link = "/ticket"



############################# social icon ############################

[[params.social]]
icon = "tf-ion-social-youtube"
link = "https://www.youtube.com/playlist?list=PLnLzwYW6HOC6rbYIcrLnVkIMdG_9WB7vn"

[[params.social]]
icon = "fas fa-envelope"
link = "mailto:hola@ccoss.org"

[[params.social]]
icon = "fa-brands fa-slack"
link = "https://sg1.run/ccoss-slack"

[[params.footer_about]]
name = "?Quién organiza¿"
link = "/team/"

[[params.footer_previous]]
name = "Prospectus"
link = "/files/CCOSS2022 Hybrid - Prospectus.pdf"

[[params.footer_previous]]
name = "Código de Conducta"
link = "/coc/"

[[params.footer_resources]]
name = "Email"
link = "mailto:hola@ccoss.org"
