######################## default configuration ####################
baseURL = "https://examplesite.org"
title = "Vixcon"
theme = "vixcon-hugo"
# post pagination
paginate = "4"
# post excerpt
summaryLength = "10"
# disqus short name
disqusShortname = "vixcon" # get your shortname form here : https://disqus.com
# disable language
disableLanguages = [] # desable language from here

# output
[outputs]
home = ["HTML", "RSS", "JSON"]

[markup.goldmark.renderer]
unsafe= true

############################# Plugins ##############################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/themefisher-font/themefisher-font.min.css"

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.js"
[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/syotimer/syotimer.min.js"
[[params.plugins.js]]
link = "plugins/search/fuse.min.js"
[[params.plugins.js]]
link = "plugins/search/mark.js"
[[params.plugins.js]]
link = "plugins/search/search.js"
[[params.plugins.js]]
link = "plugins/google-map/map.js"

############################## navigation ###############################
[menu]
    
  [[menu.main]]
  name = "About"
  URL = "about"
  weight = 2
  
  [[menu.main]]
  name = "Speakers"
  URL = "speaker"
  weight = 3

  [[menu.main]]
  weight = 4
  name = "Pages"
  hasChildren = true

    [[menu.main]]
    parent = "Pages"
    name = "Tickets"
    URL = "pricing"

    [[menu.main]]
    parent = "Pages"
    name = "Blog"
    URL = "blog"

    [[menu.main]]
    parent = "Pages"
    name = "Schedule"
    URL = "schedule"

    [[menu.main]]
    parent = "Pages"
    name = "FAQ"
    URL = "faq"
    
  [[menu.main]]
  name = "Contact"
  URL = "contact"
  weight = 5

#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Home"
# Meta data
description = "This is meta description"
author = "Themefisher"
# email address
email = "demo@vixcon.com"
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# Google Analitycs
google_analitycs_id = "" # your id
# search for blog page
search = true

# Preloader
[params.preloader]
enable = true
preloader = "" # use jpg, png, svg or gif format.

# Navigation button
[params.navigation_button]
enable = true
label = "Get Ticket"
link = "pricing"


# Subscription
[params.subscription]
enable = true
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours

# google map
[params.map]
enable = true
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyBu5nZKbeK-WHQ70oqOWo-_4VmwOwKP9YQ"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"


############################# social icon ############################
[[params.social]]
icon = "tf-ion-social-facebook"
link = "#"

[[params.social]]
icon = "tf-ion-social-twitter"
link = "#"

[[params.social]]
icon = "tf-ion-social-linkedin"
link = "#"

[[params.social]]
icon = "tf-ion-social-pinterest"
link = "#"

[[params.social]]
icon = "tf-ion-social-rss"
link = "#"


################################### English language #####################################
[Languages.en]
languageName = "En"
languageCode = "en-us"
contentDir = "content/english"
weight = 1
home = "Home"
# footer content
footer_content = "We are a creative-led experiential Event Production Agency that helps brands connect, engage and evolve."
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"


################################### French language #####################################
[Languages.fr]
languageName = "Fr"
languageCode = "fr-fr"
contentDir = "content/french"
weight = 2
home = "Accueil"
# footer content
footer_content = "We are a creative-led experiential Event Production Agency that helps brands connect, engage and evolve."
# copyright
copyright = "Copyright &copy; 2020 a hugo theme by [themefisher](https://themefisher.com)"